affine:
  base_pix_x: 0.2125
  base_pix_y: 0.2125
  base_ts_x: 1.0
  base_ts_y: 1.0
  global_shift_x: 0
  global_shift_y: 0
  target_pix_um: 1.0
cpus: 8
experiment_dirs:
  dir_id: exp_1e-05_ugrad
files:
  data_dir: ./example_data/dataset_xenium_breast1_small
  fp_dapi: ./example_data/dataset_xenium_breast1_small/morphology_mip_small.tif
  fp_neg_markers: ./example_data/sc_references/sc_breast_markers_neg.csv
  fp_pos_markers: ./example_data/sc_references/sc_breast_markers_pos.csv
  fp_ref: ./example_data/sc_references/sc_breast.csv
  fp_transcripts: ./example_data/dataset_xenium_breast1_small/transcripts_small.csv
model_params:
  elongated:
  - Endothelial
  - Fibroblasts
  - Myofibroblasts
  - SMC
  name: custom
  patch_size: 48
nuclei:
  diameter: null
nuclei_fovs:
  stitch_nuclei_fovs: false
testing_params:
  test_epoch: 1
  test_step: 60
training_params:
  aggregation: ugrad
  cc_weight: 1.0
  learning_rate: 1.0e-05
  ne_weight: 1.0
  neg_weight: 1.0
  os_weight: 1.0
  ov_weight: 1.0
  pos_weight: 1.0
  total_epochs: 5
  total_steps: 60
transcripts:
  gene_col: feature_name
  shift_to_origin: true
  transcripts_to_filter:
  - NegControlProbe_
  - antisense_
  - NegControlCodeword_
  - BLANK_
  - Blank-
  - NegPrb
  x_col: x_location
  y_col: y_location
